### PR TITLE
Mode unreachability filtering

### PR DESCRIPTION
**Pull request by 4lex4nder**

### CODE REVIEW

**Comment by danbryce** [comment]
Can you rebase the last two commits (I think those are your only changes) on my current master?  I had to clean up the tree to get it integrated into dreal3.

**Comment by danbryce** [comment]
Also, can you use the flags I already have there.  They should be -r and -e for dReach.

**Comment by 4lex4nder** [comment]
Does it work now?

**Comment by danbryce** [comment]
There are many edits to files that are not relevant.  I think something is wrong with changeset fda9ff7.  Did you combine all of the other changesets to get this one?

**Comment by 4lex4nder** [comment]
What I did was adding your fork as a remote repository on top of mine and doing a hard reset towards yours. This resulted in some minor conflicts which I resolved by hand (taking the changes from those 2 commits concerning the filtering option while taking the changes to hybrid_heuristic.cpp from the remote repository). The rest was merged automatically.
I tried doing a rebase to your fork, but this resulted in a massive amount of conflicts, since he tried to apply past (?) commits on top of the current branch...

**Comment by danbryce** [comment]
It appears that you bundled your changes with the conflict resolutions.  This makes things difficult to cleanly merge.  Is there a commit that has only your changes and not the resolutions?

**Comment by 4lex4nder** [comment]
Yeah, it's kinda messy. Can we revert and pretend this never happened? :-)
I'll do a clean reset, conflict resolution, merge and recommit of the changes when I get home (currently on mobile).
I still have the changes as manual patch files, so it shouldn't be a problem.

**Comment by danbryce** [comment]
Yes, I think that is best.

**Pull request merged**
